package com.lq.im.common.exception;

public interface ApplicationExceptionEnum {

    int SUCCESS_CODE = 200;
    String SUCCESS_MESSAGE = "成功";

    int INTERNAL_ERROR_CODE = 500;
    String INTERNAL_ERROR_MESSAGE = "服务内部错误";

    int TOO_MUCH_DATA_CODE = 20000;
    String TOO_MUCH_DATA_MESSAGE = "导入数量超出上限";

    int USER_IS_NOT_EXIST_CODE = 20001;
    String USER_IS_NOT_EXIST_MESSAGE = "用户不存在";

    int SERVER_GET_USER_ERROR_CODE = 20002;
    String SERVER_GET_USER_ERROR_MESSAGE = "服务获取用户失败";

    int MODIFY_USER_ERROR_CODE = 20003;
    String MODIFY_USER_ERROR_MESSAGE = "更新用户失败";

    int REQUEST_DATA_DOES_NOT_EXIST_CODE = 20004;
    String REQUEST_DATA_DOES_NOT_EXIST_MESSAGE = "请求数据不存在";

    int ADD_FRIEND_ERROR_CODE = 30001;
    String ADD_FRIEND_ERROR_MESSAGE = "添加好友失败";

    int OTHER_PERSON_IS_YOUR_FRIEND_CODE = 30002;
    String OTHER_PERSON_IS_YOUR_FRIEND_MESSAGE = "对方已经是你的好友";

    int OTHER_PERSON_IS_NOT_YOUR_FRIEND_CODE = 30003;
    String OTHER_PERSON_IS_NOT_YOUR_FRIEND_MESSAGE = "对方不是你的好友";

    int FRIEND_IS_DELETED_CODE = 30004;
    String FRIEND_IS_DELETED_MESSAGE = "好友已被删除";

    int FRIEND_IS_BLOCKED_CODE = 30006;
    String FRIEND_IS_BLOCKED_MESSAGE = "好友已被拉黑";

    int YOU_ARE_BLOCKED_CODE = 30007;
    String YOU_ARE_BLOCKED_MESSAGE = "你已被好友拉黑";

    int FRIENDSHIP_IS_NOT_EXIST_CODE = 30008;
    String FRIENDSHIP_IS_NOT_EXIST_MESSAGE = "好友关系不存在";

    int BLOCK_FRIEND_ERROR_CODE = 30009;
    String BLOCK_FRIEND_ERROR_MESSAGE = "添加黑名单失败";

    int FRIEND_IS_NOT_BLOCKED_CODE = 30010;
    String FRIEND_IS_NOT_BLOCKED_MESSAGE = "好友未被拉黑";

    int APPROVE_OTHERS_FRIENDSHIP_REQUEST_ERROR_CODE = 30011;
    String APPROVE_OTHERS_FRIENDSHIP_REQUEST_ERROR_MESSAGE = "无法审批其他人的好友请求";

    int FRIENDSHIP_REQUEST_IS_NOT_EXIST_CODE = 30012;
    String FRIENDSHIP_REQUEST_IS_NOT_EXIST_MESSAGE = "好友申请不存在";

    int CREATE_FRIEND_GROUP_ERROR_CODE = 30013;
    String CREATE_FRIEND_GROUP_ERROR_MESSAGE = "好友分组创建失败";

    int DELETE_FRIEND_GROUP_ERROR_CODE = 30014;
    String DELETE_FRIEND_GROUP_ERROR_MESSAGE = "好友分组删除失败";

    int FRIEND_GROUP_ALREADY_EXISTS_CODE = 30015;
    String FRIEND_GROUP_ALREADY_EXISTS_MESSAGE = "好友分组已存在";

    int FRIEND_GROUP_NOT_EXISTS_CODE = 30016;
    String FRIEND_GROUP_NOT_EXISTS_MESSAGE = "好友分组不存在";

    int FRIEND_IS_IN_GROUP_CODE = 30017;
    String FRIEND_IS_IN_GROUP_MESSAGE = "好友已在分组";

    int FRIEND_IS_NOT_IN_GROUP_CODE = 30018;
    String FRIEND_IS_NOT_IN_GROUP_MESSAGE = "好友不在分组";

    int UPDATE_FRIENDSHIP_ERROR_CODE = 30019;
    String UPDATE_FRIENDSHIP_ERROR_MESSAGE = "更新好友关系失败";

    int DELETE_FRIENDSHIP_ERROR_CODE = 30020;
    String DELETE_FRIENDSHIP_ERROR_MESSAGE = "删除好友关系失败";

    int DELETE_BLOCK_LIST_ERROR_CODE = 30020;
    String DELETE_BLOCK_LIST_ERROR_MESSAGE = "删除黑名单失败";

    int GROUP_DOES_NOT_EXIST_CODE = 40000;
    String GROUP_DOES_NOT_EXIST_MESSAGE = "群不存在";

    int GROUP_ALREADY_EXISTS_CODE = 40001;
    String GROUP_ALREADY_EXISTS_MESSAGE = "群已存在";

    int GROUP_ALREADY_HAS_OWNER_CODE = 40002;
    String GROUP_ALREADY_HAS_OWNER_MESSAGE = "群已存在群主";

    int USER_HAS_JOINED_GROUP_CODE = 40003;
    String USER_HAS_JOINED_GROUP_MESSAGE = "用户已进入该群";

    int USER_JOIN_GROUP_ERROR_CODE = 40004;
    String USER_JOIN_GROUP_ERROR_MESSAGE = "群成员添加失败";

    int TOO_MANY_GROUP_MEMBER_CODE = 40005;
    String TOO_MANY_GROUP_MEMBER_MESSAGE = "群成员数量已达到上限";

    int USER_DID_NOT_JOIN_GROUP_CODE = 40006;
    String USER_DID_NOT_JOIN_GROUP_MESSAGE = "用户不在该群";

    int THIS_OPERATION_NEEDS_MANAGER_ROLE_CODE = 40007;
    String THIS_OPERATION_NEEDS_MANAGER_ROLE_MESSAGE = "该操作只允许群主/管理员完成";

    int THIS_OPERATION_NEEDS_APP_MANAGER_ROLE_CODE = 40008;
    String THIS_OPERATION_NEEDS_APP_MANAGER_ROLE_MESSAGE = "该操作只允许APP管理员完成";

    int THIS_OPERATION_NEEDS_OWNER_ROLE_CODE = 40009;
    String THIS_OPERATION_NEEDS_OWNER_ROLE_MESSAGE = "该操作只允许群主完成";

    int CAN_NOT_REMOVE_GROUP_OWNER_CODE = 40010;
    String CAN_NOT_REMOVE_GROUP_OWNER_MESSAGE = "无法移除群主";

    int UPDATE_GROUP_BASE_INFO_ERROR_CODE = 40011;
    String UPDATE_GROUP_BASE_INFO_ERROR_MESSAGE = "更新群信息失败";

    int GROUP_IS_MUTED_CODE = 40012;
    String GROUP_IS_MUTED_MESSAGE = "该群已开启禁言";

    int IMPORT_GROUP_ERROR_CODE = 40013;
    String IMPORT_GROUP_ERROR_MESSAGE = "导入群组失败";

    int THIS_OPERATION_NEEDS_ONESELF_CODE = 40014;
    String THIS_OPERATION_NEEDS_ONESELF_MESSAGE = "该操作只允许自己操作";

    int CAN_NOT_DISMISS_PRIVATE_GROUP_CODE = 40015;
    String CAN_NOT_DISMISS_PRIVATE_GROUP_MESSAGE = "私有群不允许解散";

    int PUBLIC_GROUP_MUST_HAVE_OWNER_CODE = 40016;
    String PUBLIC_GROUP_MUST_HAVE_OWNER_MESSAGE = "公开群必须指定群主";

    int GROUP_MEMBER_IS_MUTED_CODE = 40017;
    String GROUP_MEMBER_IS_MUTED_MESSAGE = "群成员被禁言";

    int GROUP_IS_DISMISSED_CODE = 40018;
    String GROUP_IS_DISMISSED_MESSAGE = "群已被解散";

    int CREATE_GROUP_ERROR_CODE = 40019;
    String CREATE_GROUP_ERROR_MESSAGE = "群组创建失败";

    int GET_GROUP_MEMBER_ERROR_CODE = 40020;
    String GET_GROUP_MEMBER_ERROR_MESSAGE = "获取群组用户失败";

    int GET_JOINED_GROUP_ERROR_CODE = 40021;
    String GET_JOINED_GROUP_ERROR_MESSAGE = "获取已加入的群组失败";

    int DISMISS_GROUP_ERROR_CODE = 40022;
    String DISMISS_GROUP_ERROR_MESSAGE = "解散群组失败";

    int SERVER_NOT_AVAILABLE_CODE = 71000;
    String SERVER_NOT_AVAILABLE_MESSAGE = "没有可用的服务";

    int PARAMETER_VALIDATION_ERROR_CODE = 90001;
    String PARAMETER_VALIDATION_ERROR_MESSAGE = "请求参数解析失败";

    int getCode();

    String getError();
}
