im:
  tcpPort: 9000
  websocketPort: 19000
  bossThreadSize: 1
  workerThreadSize: 8
  timeout: 3000
  brokerId: 1000
  loginMode: 3
  logicUrl: http://127.0.0.1:8000/api/v1

  redis:
    mode: single
    database: 0
    password: 123456
    timeout: 3000
    poolMinIdle: 8
    poolConnTimeout: 3000
    poolSize: 10
    single:
      address: 192.168.145.128:6379
  rabbitmq:
    host: 192.168.145.128
    port: 5672
    username: admin
    password: 123456
    virtualHost: /
  zooKeeper:
    host: 192.168.145.128:2181
    connectTimeout: 5000