im:
  tcpPort: 9001
  websocketPort: 19001
  bossThreadSize: 1
  workerThreadSize: 8
  timeout: 3000
  brokerId: 1001
  loginMode: 1

  redis:
    mode: single
    database: 0
    password: 123456
    timeout: 3000
    poolMinIdle: 8
    poolConnTimeout: 3000
    poolSize: 10
    single:
      address: 192.168.145.128:6379
  rabbitmq:
    host: 192.168.145.128
    port: 5672
    username: admin
    password: 123456
    virtualHost: /
  zooKeeper:
    host: 192.168.145.128:2181
    connectTimeout: 5000