spring:
  profiles:
    active: dev

# logger 配置
logging:
  config: classpath:logback-spring.xml

server:
  port: 8000

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml
  global-config:
    db-config:
      update-strategy: NOT_EMPTY

router:
  routeStrategy: 0
  hashingStrategy: 1

appConfig:
  privateKey: 123456

httpclient:
  maxTotal: 100
  defaultMaxPerRoute: 50
  connectTimeout: 2000
  socketTimeout: 5000
  checkStaleConnection: true

  callbackUrl: "http://127.0.0.1:8001/callback"
  afterUserInfoModified: false
  beforeAddFriendship: false
  afterAddFriendship: false
  afterModifyFriendship: false
  afterDeleteFriendship: false
  afterBlockFriend: false
  afterUnblockFriend: false
  afterCreateChatGroup: false
  afterModifyChatGroup: false
  afterDismissChatGroup: false
  afterDeleteChatGroupMember: false
  beforeAddChatGroupMember: false
  afterAddChatGroupMember: false
  
