package com.lq.im.common.enums;

import com.lq.im.common.exception.ApplicationExceptionEnum;

public enum GroupErrorCodeEnum implements ApplicationExceptionEnum {
    GROUP_DOES_NOT_EXIST(GROUP_DOES_NOT_EXIST_CODE, GROUP_DOES_NOT_EXIST_MESSAGE),

    GROUP_ALREADY_EXISTS(GROUP_ALREADY_EXISTS_CODE, GROUP_ALREADY_EXISTS_MESSAGE),

    GROUP_ALREADY_HAS_OWNER(GROUP_ALREADY_HAS_OWNER_CODE, GROUP_ALREADY_HAS_OWNER_MESSAGE),

    USER_HAS_JOINED_GROUP(USER_HAS_JOINED_GROUP_CODE, USER_HAS_JOINED_GROUP_MESSAGE),

    USER_JOIN_GROUP_ERROR(USER_JOIN_GROUP_ERROR_CODE, USER_JOIN_GROUP_ERROR_MESSAGE),

    TOO_MANY_GROUP_MEMBER(TOO_MANY_GROUP_MEMBER_CODE, TOO_MANY_GROUP_MEMBER_MESSAGE),

    USER_DID_NOT_JOIN_GROUP(USER_DID_NOT_JOIN_GROUP_CODE, USER_DID_NOT_JOIN_GROUP_MESSAGE),

    THIS_OPERATION_NEEDS_MANAGER_ROLE(THIS_OPERATION_NEEDS_MANAGER_ROLE_CODE, THIS_OPERATION_NEEDS_MANAGER_ROLE_MESSAGE),

    THIS_OPERATION_NEEDS_APP_MANAGER_ROLE(THIS_OPERATION_NEEDS_APP_MANAGER_ROLE_CODE, THIS_OPERATION_NEEDS_APP_MANAGER_ROLE_MESSAGE),

    THIS_OPERATION_NEEDS_OWNER_ROLE(THIS_OPERATION_NEEDS_OWNER_ROLE_CODE, THIS_OPERATION_NEEDS_OWNER_ROLE_MESSAGE),

    CAN_NOT_REMOVE_GROUP_OWNER(CAN_NOT_REMOVE_GROUP_OWNER_CODE, CAN_NOT_REMOVE_GROUP_OWNER_MESSAGE),

    UPDATE_GROUP_BASE_INFO_ERROR(UPDATE_GROUP_BASE_INFO_ERROR_CODE, UPDATE_GROUP_BASE_INFO_ERROR_MESSAGE),

    GROUP_IS_MUTED(GROUP_IS_MUTED_CODE, GROUP_IS_MUTED_MESSAGE),

    IMPORT_GROUP_ERROR(IMPORT_GROUP_ERROR_CODE, IMPORT_GROUP_ERROR_MESSAGE),

    THIS_OPERATION_NEEDS_ONESELF(THIS_OPERATION_NEEDS_ONESELF_CODE, THIS_OPERATION_NEEDS_ONESELF_MESSAGE),

    CAN_NOT_DISMISS_PRIVATE_GROUP(CAN_NOT_DISMISS_PRIVATE_GROUP_CODE, CAN_NOT_DISMISS_PRIVATE_GROUP_MESSAGE),

    PUBLIC_GROUP_MUST_HAVE_OWNER(PUBLIC_GROUP_MUST_HAVE_OWNER_CODE, PUBLIC_GROUP_MUST_HAVE_OWNER_MESSAGE),

    GROUP_MEMBER_IS_MUTED(GROUP_MEMBER_IS_MUTED_CODE, GROUP_MEMBER_IS_MUTED_MESSAGE),

    GROUP_IS_DISMISSED(GROUP_IS_DISMISSED_CODE, GROUP_IS_DISMISSED_MESSAGE),

    CREATE_GROUP_ERROR(CREATE_GROUP_ERROR_CODE, CREATE_GROUP_ERROR_MESSAGE),

    GET_GROUP_MEMBER_ERROR(GET_GROUP_MEMBER_ERROR_CODE, GET_GROUP_MEMBER_ERROR_MESSAGE),

    GET_JOINED_GROUP_ERROR(GET_JOINED_GROUP_ERROR_CODE, GET_JOINED_GROUP_ERROR_MESSAGE),

    DISMISS_GROUP_ERROR(DISMISS_GROUP_ERROR_CODE, DISMISS_GROUP_ERROR_MESSAGE),
    ;

    private final int code;
    private final String error;

    GroupErrorCodeEnum(int code, String error){
        this.code = code;
        this.error = error;
    }

    @Override
    public int getCode() {
        return this.code;
    }

    @Override
    public String getError() {
        return this.error;
    }
}
