package com.lq.im.common.enums.friendship;

import com.lq.im.common.exception.ApplicationExceptionEnum;

public enum FriendShipErrorCodeEnum implements ApplicationExceptionEnum {
    TOO_MUCH_DATA(TOO_MUCH_DATA_CODE, TOO_MUCH_DATA_MESSAGE),
    ADD_FRIEND_ERROR(ADD_FRIEND_ERROR_CODE, ADD_FRIEND_ERROR_MESSAGE),
    OTHER_PERSON_IS_YOUR_FRIEND(OTHER_PERSON_IS_YOUR_FRIEND_CODE, OTHER_PERSON_IS_YOUR_FRIEND_MESSAGE),
    OTHER_PERSON_IS_NOT_YOUR_FRIEND(OTHER_PERSON_IS_NOT_YOUR_FRIEND_CODE, OTHER_PERSON_IS_NOT_YOUR_FRIEND_MESSAGE),
    FRIEND_IS_DELETED(FRIEND_IS_DELETED_CODE, FRIEND_IS_DELETED_MESSAGE),
    FRIEND_IS_BLOCKED(FRIEND_IS_BLOCKED_CODE, FRIEND_IS_BLOCKED_MESSAGE),
    YOU_ARE_BLOCKED(YOU_ARE_BLOCKED_CODE, YOU_ARE_BLOCKED_MESSAGE),
    FRIENDSHIP_IS_NOT_EXIST(FRIENDSHIP_IS_NOT_EXIST_CODE, FRIENDSHIP_IS_NOT_EXIST_MESSAGE),
    BLOCK_FRIEND_ERROR(BLOCK_FRIEND_ERROR_CODE, BLOCK_FRIEND_ERROR_MESSAGE),
    FRIEND_IS_NOT_BLOCKED(FRIEND_IS_NOT_BLOCKED_CODE, FRIEND_IS_NOT_BLOCKED_MESSAGE),
    APPROVE_OTHERS_FRIENDSHIP_REQUEST_ERROR(APPROVE_OTHERS_FRIENDSHIP_REQUEST_ERROR_CODE,
            APPROVE_OTHERS_FRIENDSHIP_REQUEST_ERROR_MESSAGE),
    FRIENDSHIP_REQUEST_IS_NOT_EXIST(FRIENDSHIP_REQUEST_IS_NOT_EXIST_CODE, FRIENDSHIP_REQUEST_IS_NOT_EXIST_MESSAGE),
    CREATE_FRIEND_GROUP_ERROR(CREATE_FRIEND_GROUP_ERROR_CODE, CREATE_FRIEND_GROUP_ERROR_MESSAGE),
    DELETE_FRIEND_GROUP_ERROR(DELETE_FRIEND_GROUP_ERROR_CODE, DELETE_FRIEND_GROUP_ERROR_MESSAGE),
    FRIEND_GROUP_ALREADY_EXISTS(FRIEND_GROUP_ALREADY_EXISTS_CODE, FRIEND_GROUP_ALREADY_EXISTS_MESSAGE),
    FRIEND_GROUP_NOT_EXISTS(FRIEND_GROUP_NOT_EXISTS_CODE, FRIEND_GROUP_NOT_EXISTS_MESSAGE),
    FRIEND_IS_IN_GROUP(FRIEND_IS_IN_GROUP_CODE, FRIEND_IS_IN_GROUP_MESSAGE),
    FRIEND_IS_NOT_IN_GROUP(FRIEND_IS_NOT_IN_GROUP_CODE,  FRIEND_IS_NOT_IN_GROUP_MESSAGE),
    UPDATE_FRIENDSHIP_ERROR(UPDATE_FRIENDSHIP_ERROR_CODE, UPDATE_FRIENDSHIP_ERROR_MESSAGE),
    DELETE_FRIENDSHIP_ERROR(DELETE_FRIENDSHIP_ERROR_CODE, DELETE_FRIENDSHIP_ERROR_MESSAGE),
    DELETE_BLOCK_LIST_FAIL(DELETE_BLOCK_LIST_ERROR_CODE, DELETE_BLOCK_LIST_ERROR_MESSAGE),
    REQUEST_DATA_DOES_NOT_EXIST(REQUEST_DATA_DOES_NOT_EXIST_CODE, REQUEST_DATA_DOES_NOT_EXIST_MESSAGE),
    ;

    private final int code;

    private final String error;

    FriendShipErrorCodeEnum(int code, String error) {
        this.code = code;
        this.error = error;
    }

    @Override
    public int getCode() {
        return this.code;
    }

    @Override
    public String getError() {
        return this.error;
    }
}
